package com.example.aftas.domain.enums;

public enum AuthorityEnum {

    GRANT_AUTHORITY_TO_ROLE,
    REVOKE_AUTHORITY_FROM_ROLE,
    ASSIGN_ROLE_TO_USER,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    VIEW_ROLES,
    UPDATE_USERS,
    VIEW_USERS,
    DELETE_USERS,
    VIEW_AUTHORITIES ,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    VIEW_PRODUCTS,
    CREATE_DEVICE_TYPE,
    UPDATE_DEVICE_TYPE,
    DELETE_DEVICE_TYPE,
    VIEW_DEVICE_TYPES,

}
