package com.example.aftas.domain.enums;

public enum AuthorityEnum {

    GRANT_AUTHORITY_TO_ROLE,
    REVOKE_AUTHORITY_FROM_ROLE,
    ASSIGN_ROLE_TO_USER,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    VIEW_ROLES,
    UPDATE_USERS,
    VIEW_USERS,
    DELETE_USERS,
    VIEW_AUTHORITIES ,

    CREATE_COMPETITION,
    UPDATE_COMPETITION,
    DELETE_COMPETITION,
    VIEW_COMPETITIONS,

    ADD_FISHING,
    UPDATE_FISHING,
    DELETE_FISHING,
    VIEW_FISHINGS,

    CREATE_MEMBER,
    UPDATE_MEMBER,
    DELETE_MEMBER,
    VIEW_MEMBERS,

    MANAGE_MEMBER,
}
